version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "Github CI/CD"
      - "no releasenotes"
  - package-ecosystem: "cargo"
    directory: "/rust"
    schedule:
      interval: "weekly"
