[project]
authors = ["Adrian Seyboldt <adrian.seyboldt@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "nuts-py"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
test = "pytest"
develop = "maturin develop --release"

[dependencies]
python = ">=3.12.7,<3.13"
pymc = ">=5.18.0,<5.19"
numba = ">=0.60.0,<0.61"
pytest = ">=8.3.3,<9"
maturin = ">=1.7.4,<2"
pip = ">=24.3.1,<25"
#jax = ">=0.4.34,<0.5"
ipykernel = ">=6.29.5,<7"
seaborn = ">=0.13.2,<0.14"
threadpoolctl = ">=3.5.0,<4"
zarr = ">=2.18.3,<3"
polars = ">=1.12.0,<2"
# The jaxlib cuda build seems to be broken around version 0.4.34
#jaxlib = { version = "*", build = "*cuda12*" }

[pypi-dependencies]
bridgestan = ">=2.5.0, <3"
#flowjax = { git = "https://github.com/aseyboldt/flowjax.git", rev = "1c282f2ded78e81c7ce6a96f61523a9f18bf8edc" }
flowjax = { path = "../flowjax/", editable = true }
samplerlab = { path = "../pymc-labs/benchmark-pymc", editable = true }
posteriordb = ">=0.2.0, <0.3"
jax = { version = "==0.4.35", extras = ["cuda12"] }
watermark = ">=2.5.0, <3"

[system-requirements]
#cuda = "12"
