[project]
authors = ["Adrian Seyboldt <adrian.seyboldt@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "nuts-py"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
test = "pytest"
develop = "maturin develop --release"
get-posteriordb = "git clone 'https://github.com/stan-dev/posteriordb'"

[tasks.bench]
depends-on = ["develop", "get-posteriordb"]
cmd = "python -m samplerlab -m posteriordb-fast --posteriordb posteriordb/posterior_database --save-traces --seed 12345"

[dependencies]
python = ">=3.12.7,<3.13"
pymc = ">=5.19.0,<6"
numba = ">=0.60.0,<0.61"
pytest = ">=8.3.4,<9"
maturin = ">=1.7.7,<2"
pip = ">=24.3.1,<25"
ipykernel = ">=6.29.5,<7"
seaborn = ">=0.13.2,<0.14"
threadpoolctl = ">=3.5.0,<4"
zarr = ">=2.18.3,<3"
polars = ">=1.16.0,<2"
viztracer = ">=1.0.0,<2"
ipywidgets = ">=8.1.5,<9"
# The jaxlib cuda build seems to be broken around version 0.4.34
#jax = ">=0.4.35,<0.5"
#jaxlib = { version = "*", build = "*cuda12*" }

[pypi-dependencies]
bridgestan = ">=2.6.0, <3"
flowjax = { git = "https://github.com/aseyboldt/flowjax.git", rev = "07e7e32217bcfcaa7d68a304f332c925d26ab76f" }
samplerlab = { git = "https://github.com/aseyboldt/samplerlab/" }
posteriordb = ">=0.2.0, <0.3"
jax = { version = "<0.4.37, <0.5", extras = ["cuda12"] }
watermark = ">=2.5.0, <3"

[system-requirements]
#cuda = "12"
